---
development:
  cloud_name: ENV["CLOUDNAME"]
  api_key: ENV["API_KEY"]
  api_secret: ENV["API_SECRET"]
  enhance_image_tag: true
  static_file_support: false
test:
  cloud_name: ENV["CLOUDNAME"]
  api_key: ENV["API_KEY"]
  api_secret: ENV["API_SECRET"]
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: ENV["CLOUDNAME"]
  api_key: ENV["API_KEY"]
  api_secret: ENV["API_SECRET"]
  enhance_image_tag: true
  static_file_support: false

