meta_product_name: "Boutique B."
meta_title: "Boutique B. - Atelier Blob"
meta_description: "Boutique B. est un vraiment super projet d'éditions d'art initié par Atelier Blob avec Clara Flores, Chloe Tournoux et Paul Lahana"
meta_image: "boutiqueblob.png" # should exist in `app/assets/images/`
